version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: poscloud
      MINIO_ROOT_PASSWORD: elposcrece05
      MINIO_SERVER_URL: https://minio.example.com.ar:9000
    hostname: minio.example.com.ar
    volumes:
      - /home/minio/data:/data
      - /home/minio/config:/root/.minio
      - /home/minio/certs:/root/.minio/certs
    command: server /data --console-address ":9001"

